baseurl: /
exclude:
  - LICENSE.md
permalink: pretty
sass:
  style: compressed

title: Disable Gatekeeper on macOS Catalina (10.15)
description: Disable or restore macOS Gatekeeper by following the instructions on this website.
